[phases.setup]
nixPkgs = ['php83', 'php83Packages.composer', 'php83Extensions.mongodb']

[phases.build]
cmds = ['composer install --no-dev --optimize-autoloader']

[start]
cmd = 'php -S 0.0.0.0:$PORT'